### ISSUE TITLE
Depending on unknown package zodern:types

### ISSUE THREAD

**Issue by piotrpospiech** [zodern/meteor-types#3]
I was adding `zodern:types` to meteor core packages and I got an error. There are several packages that don't work with the current version of the package. For example package `fetch`. I added `api.use('zodern:types')` to the `packages/fetch/package.js` in the local meteor repo and after that my project threw an error when I started it. 

The error is the same with other packages that doesn't work with this package. When I added `zodern:types` as one of the meteor core packages, it worked without any problems.

<details>
<summary markdown="span">Screenshot</summary>

![image](https://user-images.githubusercontent.com/37746259/185098517-36cda127-fee6-42a8-877e-580ba269d9c0.png)

</details>

**Comment by zodern** [comment]
This looks like it might be because you can't use any community packages in the packages part of the `combined` isopacket: https://github.com/meteor/meteor/blob/ffcfa5062cf1bf8a64ea64fef681ffcd99fe7939/tools/tool-env/isopackets.js#L52-L74.
Fetch is part of combined because it is a dependency of ejson > ecmascript > dynamic-import > fetch.

**Comment by piotrpospiech** [comment]
I found out that I can add only `.d.ts` files and `package-types.json` file with `typesEntry` without adding this package as a dependency because it will be needed only in the user's project. For this reason, this issue and https://github.com/zodern/meteor-types/issues/4 are no longer a problem.
