### ISSUE TITLE
Circular dependency between packages

### ISSUE THREAD

**Issue by piotrpospiech** [zodern/meteor-types#4]
I tried to add `zodern:types` to the meteor core package - `meteor`. I got this [error](https://github.com/zodern/meteor-types/issues/3) first, but after I added `zodern:types` as the core package, I ran into another issue. I think it will be a problem also with the externally working `zodern:types` package.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/37746259/185106149-5d1ae46f-0a84-454e-8379-51abb2b90086.png)

</details>

**Comment by zodern** [comment]
All Meteor packages have an implicit dependency on `meteor`. Does it work if you instead use:
```
api.use('zodern:types', {unordered: true});
```

If that doesn't, I can make `meteor` an unordered dep of `zodern:types`.

**Comment by zodern** [comment]
Actually, it will be more complicated than this since `zodern:types` also depends on `modules`, which it and its dependencies depends on `meteor`.

What are you trying to achieve, and what are your short term goals? I didn't design `zodern:types` to work for core packages, and there might be are easier and better ways to achieve what you are wanting to do.
